# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(800, 650)
        Login.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_3 = QtWidgets.QLabel(Login)
        self.label_3.setGeometry(QtCore.QRect(140, 10, 521, 61))
        self.label_3.setStyleSheet("border-image: url(../../../Downloads/GUI files-20230410T095706Z-001/GUI files/KartisTechnology(white).png);\n"
"background-color:transparent;")
        self.label_3.setText("")
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(Login)
        self.label.setGeometry(QtCore.QRect(140, 80, 531, 511))
        self.label.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 30px;\n"
"border-width: 5px 5px 5px 5px;\n"
"border-style: solid;")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Login)
        self.pushButton.setGeometry(QtCore.QRect(170, 470, 141, 61))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("border-image: url(../../../Downloads/GUI files-20230410T095706Z-001/GUI files/retry.png);\n"
"background-color: transparent;")
        self.pushButton.setText("")
        self.pushButton.setAutoDefault(False)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_3 = QtWidgets.QPushButton(Login)
        self.pushButton_3.setGeometry(QtCore.QRect(500, 470, 141, 61))
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setStyleSheet("border-image: url(../../../Downloads/GUI files-20230410T095706Z-001/GUI files/exit.png);\n"
"background-color: transparent;")
        self.pushButton_3.setText("")
        self.pushButton_3.setAutoDefault(False)
        self.pushButton_3.setObjectName("pushButton_3")
        self.username_edit = QtWidgets.QLineEdit(Login)
        self.username_edit.setGeometry(QtCore.QRect(200, 170, 411, 71))
        self.username_edit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.username_edit.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"color: white;\n"
"font: 18pt \"Impact\";\n"
"border-radius: 25px;\n"
"padding: 15px;\n"
"border-width: 5px 5px 5px 5px;\n"
"border-style: solid;")
        self.username_edit.setObjectName("username_edit")
        self.password_edit = QtWidgets.QLineEdit(Login)
        self.password_edit.setGeometry(QtCore.QRect(200, 270, 411, 71))
        self.password_edit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.password_edit.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"color: white;\n"
"font: 18pt \"Impact\";\n"
"border-radius: 25px;\n"
"padding: 15px;\n"
"border-width: 5px 5px 5px 5px;\n"
"border-style: solid;")
        self.password_edit.setObjectName("password_edit")
        self.pushButton_4 = QtWidgets.QPushButton(Login)
        self.pushButton_4.setGeometry(QtCore.QRect(320, 380, 171, 61))
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_4.setStyleSheet("border-image: url(../../../Downloads/GUI files-20230410T095706Z-001/GUI files/login-empty.png);")
        self.pushButton_4.setText("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_2 = QtWidgets.QLabel(Login)
        self.label_2.setGeometry(QtCore.QRect(160, 110, 491, 341))
        self.label_2.setStyleSheet("border-image: url(../../../Downloads/GUI files-20230410T095706Z-001/GUI files/illegalEntry.gif);")
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "LoginForm"))
        self.label.setText(_translate("Login", "TextLabel"))
        self.username_edit.setPlaceholderText(_translate("Login", "USERNAME"))
        self.password_edit.setPlaceholderText(_translate("Login", "PASSWORD"))
        self.label_2.setText(_translate("Login", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Login = QtWidgets.QWidget()
    ui = Ui_Login()
    ui.setupUi(Login)
    Login.show()
    sys.exit(app.exec_())
